<a href="https://colab.research.google.com/github/shubhika1723/shubhika_INFO5731_Spring2020/blob/main/In_class_exercise_03_10062022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The third In-class-exercise (10/06/2022, 40 points in total)

The purpose of this exercise is to understand text representation.

Question 1 (10 points): Describe an interesting text classification or text mining task and explain what kind of features might be useful for you to build the machine learning model. List your features and explain why these features might be helpful. You need to list at least five different types of features.

In [ ]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:

Unstructured text is converted into structured data by the process of text mining, sometimes referred to as text analysis, to facilitate analysis. 
Natural language processing (NLP) is a technique used in text mining to help computers automatically understand and analyze human language.

Text classification is the process of assigning categories (tags) to unstructured text data. It is simple to organize and organize complex language into meaningful data. 
Businesses may rapidly and cheaply get valuable information by utilizing text classification to evaluate a variety of data, including emails and support tickets.

Task:
Text classifiers can automatically identify the goals or purposes underlying a text through the process of "intent detection." When examining client chats, this can be quite helpful. By sorting through various outbound sales email answers, you might, for instance, separate the prospects who are interested in your product from those who are not or who want to unsubscribe.

1.Word2vec features 
2.Linguistic feature extraction
3.Dependency Parse 
4. Tfidf 
5.Entity feature

'''

Question 2 (20 points): Write python code to extract these features you discussed above. You can collect a few sample text data for the feature extraction.

In [1]:
# You code here (Please add comments in the code):

import nltk

from bs4 import BeautifulSoup as bs
import pandas as pd
import requests as rq
import matplotlib.pyplot as plt
import nltk
from wordcloud import WordCloud
from nltk.corpus import stopwords


#collecting sample text data from IMDb "BheemlaNaik movie reviews"

#assigining the URL to a varilable 
url = 'https://www.imdb.com/title/tt10733228/reviews/?ref_=tt_ql_urv'

#Creating a data frame with one column to store text of reviews
data_frame = pd.DataFrame(columns=['Review'])
req = rq.get(url).text
soup = bs(req,'html.parser')

#collecting reviews text
review_text = soup.find_all('div', attrs={'class' : 'text show-more__control'})

#creating a empty list
review_list = []
for i in range(len(review_text)):
    review_list.append(review_text[i].get_text())

#assigining list to the data frame    
data_frame['Review'] = review_list

data_frame['word_count'] = data_frame['Review'].apply(lambda x: len(str(x).split(" ")))
data_frame[['Review','word_count']].head()

                                              Review  word_count
0  The only objective of making such a movie is t...         154
1  The weakest part of Gehraiyaan, I thought, was...         168
2  Seriously This Movie is not Written and Direct...          39
3  Gehraiyaan is the movie where there is no 'Geh...         219
4  Characters: Not RelatableI am not saying that ...         201

In [2]:
data_frame['char_count'] = data_frame['Review'].str.len() ## this also includes spaces
data_frame[['Review','char_count']].head()

                                              Review  char_count
0  The only objective of making such a movie is t...         890
1  The weakest part of Gehraiyaan, I thought, was...        1052
2  Seriously This Movie is not Written and Direct...         249
3  Gehraiyaan is the movie where there is no 'Geh...        1141
4  Characters: Not RelatableI am not saying that ...        1196

In [3]:

from nltk.corpus import stopwords

import nltk
nltk.download('stopwords')
stop = stopwords.words('english')

data_frame['stopwords'] = data_frame['Review'].apply(lambda x: len([x for x in x.split() if x in stop]))
data_frame[['Review','stopwords']].head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

                                              Review  stopwords
0  The only objective of making such a movie is t...         59
1  The weakest part of Gehraiyaan, I thought, was...         60
2  Seriously This Movie is not Written and Direct...          7
3  Gehraiyaan is the movie where there is no 'Geh...        103
4  Characters: Not RelatableI am not saying that ...         84

In [4]:
data_frame['hastags'] = data_frame['Review'].apply(lambda x: len([x for x in x.split() if x.startswith('#')]))
data_frame[['Review','hastags']].head()

                                              Review  hastags
0  The only objective of making such a movie is t...        0
1  The weakest part of Gehraiyaan, I thought, was...        0
2  Seriously This Movie is not Written and Direct...        0
3  Gehraiyaan is the movie where there is no 'Geh...        0
4  Characters: Not RelatableI am not saying that ...        0

In [5]:
data_frame['numerics'] = data_frame['Review'].apply(lambda x: len([x for x in x.split() if x.isdigit()]))
data_frame[['Review','numerics']].head()

                                              Review  numerics
0  The only objective of making such a movie is t...         0
1  The weakest part of Gehraiyaan, I thought, was...         0
2  Seriously This Movie is not Written and Direct...         1
3  Gehraiyaan is the movie where there is no 'Geh...         1
4  Characters: Not RelatableI am not saying that ...         0

In [6]:
data_frame['upper'] = data_frame['Review'].apply(lambda x: len([x for x in x.split() if x.isupper()]))
data_frame[['Review','upper']].head()

                                              Review  upper
0  The only objective of making such a movie is t...      1
1  The weakest part of Gehraiyaan, I thought, was...      1
2  Seriously This Movie is not Written and Direct...      0
3  Gehraiyaan is the movie where there is no 'Geh...      4
4  Characters: Not RelatableI am not saying that ...     15

Question 3 (10 points): Use any of the feature selection methods mentioned in this paper "Deng, X., Li, Y., Weng, J., & Zhang, J. (2019). Feature selection for text classification: A review. Multimedia Tools & Applications, 78(3)." Select the most important features you extracted above, rank the features based on their importance in the descending order.

In [7]:
# You code here (Please add comments in the code):
text_classifcation = (data_frame['Review'][1:2]).apply(lambda x: pd.value_counts(x.split(" "))).sum(axis = 0).reset_index()
text_classifcation.columns =['words', 'tf']
text_classifcation

            words  tf
0             the   8
1             and   8
2               a   5
3              of   5
4             The   3
..            ...  ..
126      feelings   1
127     struggles   1
128  contemporary   1
129         done.   1
130         down.   1

[131 rows x 2 columns]

In [ ]:
import numpy as np 

for i,word in enumerate(text_classifcation['words']):
  text_classifcation.loc[i, 'idf'] = np.log(data_frame.shape[0]/(len(data_frame[data_frame['Review'].str.contains(word)])))

text_classifcations

In [17]:
text_classifcation['tfidf'] = text_classifcation['tf'] + text_classifcation['idf']
text_classifcation

            words  tf       idf     tfidf
0             the   8  0.127833  8.127833
1             and   8  0.274437  8.274437
2               a   5  0.000000  5.000000
3              of   5  0.385662  5.385662
4             The   3  0.653926  3.653926
..            ...  ..       ...       ...
126      feelings   1       NaN       NaN
127     struggles   1       NaN       NaN
128  contemporary   1       NaN       NaN
129         done.   1       NaN       NaN
130         down.   1       NaN       NaN

[131 rows x 4 columns]